//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NewUser
    {
        public int Id { get; set; }
        [Required(ErrorMessage="Enter your Name")]
        [DataType(DataType.Text)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter your Email")]
        [DataType(DataType.EmailAddress)]   
        public string email { get; set; }
        [Required(ErrorMessage = "Enter your City")]
        [DataType(DataType.Text)]   
        public string City { get; set; }
        [Required(ErrorMessage = "Enter your Password")]
        [DataType(DataType.Password)]   
        public string password { get; set; }
        [Required(ErrorMessage = "Confirm the Password ")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Not Matching")]
        public string confirmpass { get; set; }
    }
}
