using EF1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EF1.Configurations
{
    internal class BlogConfig:IEntityTypeConfiguration<Blog>
    {
       
        public void Configure(EntityTypeBuilder<Blog> builder)
        {
            builder.Property(p=>p.Url).IsRequired().HasMaxLength(100);

            //*** Index
            //builder.HasIndex(p => p.Url).IsUnique(true);
            //builder.HasIndex(p => p.Url).HasFilter("Url Is Not NULL"); // add query filter

            //builder.HasIndex(p => p.Url).IsUnique(true).HasDatabaseName("Test");// to change the name of index in DB
            //builder.HasIndex(p => new {p.Url, p.Name }).IsUnique(true).HasName("Compo_IX");//create new index with new name

            //*** data seeding => adding data(information) to table (as city names,ZIP,country ,...
            //builder.HasData(new Blog { Id = 1, Name = "fatacat", Url = "www.google.com" });// u must add all properties even the autogenerated prop


        }
    }
}
