// <auto-generated />
using System;
using ConsoleProj;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleProj.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230911094139_TpHEx02")]
    partial class TpHEx02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleProj.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<bool>("IsEmployee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConsoleProj.Student", b =>
                {
                    b.HasBaseType("ConsoleProj.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue(false);
                });

            modelBuilder.Entity("ConsoleProj.Teacher", b =>
                {
                    b.HasBaseType("ConsoleProj.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.ToTable("People", t =>
                        {
                            t.Property("HireDate")
                                .HasColumnName("Teacher_HireDate");
                        });

                    b.HasDiscriminator().HasValue(true);
                });
#pragma warning restore 612, 618
        }
    }
}
